name: NPM Install Check

on:
  push:
    branches:
      - main # Branch you want to trigger on
  pull_request:
    branches:
      - main # Branch you want to trigger on

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.2.0" # Change to the version of Node.js you are using

      - name: Install dependencies
        run: npm install

      - name: Run script dev to check for npm install
        run: npm run dev

        # Check if the process is running (this checks if npm run dev worked)
      - name: Verify the app is running
        run: |
          if ! pgrep -f "npm run dev" > /dev/null; then
            echo "npm run dev did not run correctly" && exit 1
          fi
